sensors:
  luftdaten:
    17314:
      name: Westminster Road, Easton
      start_date: 2018-10-06
      location:
        latitude: 51.4633
        longitude: -2.5549

    17316:
      name: Emmaus - Backfields House
      start_date: 2018-10-06
      location:
        latitude: 51.4608
        longitude: -2.5885

    17318:
      name: Emmaus - Shaftesbury House
      start_date: 2018-10-06
      location:
        latitude: 51.4525
        longitude: -2.5746

    17502:
      name: St Werburghs
      start_date: 2018-10-14
      location:
        latitude: 51.468
        longitude: -2.5718

    17459:
      name: St Paul's Learning Centre
      start_date: 2018-10-15
      location:
        latitude: 51.464363
        longitude: -2.582494

    19613:
      name: St Paul's Adventure Playground
      start_date: 2018-12-23
      location:
        latitude: 51.4649
        longitude: -2.5776

    17506:
      name: Easton Community Centre
      start_date: 2018-10-14
      location:
        latitude: 51.461797
        longitude: -2.562962
        
    19615:
      name: Bannerman School
      start_date: 2018-12-23
      location:
        latitude: 51.4638
        longitude: -2.5646              
